## Register user
POST http://localhost:3900/auth/register
Content-Type: application/json

{
    "fullName": "Kenny Maina",
    "email": "kennynet66@gmail.com",
    "password": "12345678"
}

### login a user
POST http://localhost:3900/auth/login
Content-Type: application/json

{
    "email": "gillgates@gmail.com",
    "password": "test12"
}

### verify user
PUT http://localhost:3900/auth/validate-user/5bb8a9a3-885c-4fc5-88e1-e4315cc953fe

### check user details
GET http://localhost:3900/auth/details
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiY2NkYjYwNy05MDc3LTQyZjYtOThhNy1lNzc3ZGRhNWVjZTQiLCJmdWxsTmFtZSI6Imtlbm55IG1haW5hIiwiZW1haWwiOiJka2luZ3MxMjNAeW9wbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwicm9sZSI6InVzZXIiLCJwcm9maWxlSW1nIjpudWxsLCJpYXQiOjE3MTA1MjA1ODQsImV4cCI6MTcxMDYyNDI2NH0.swCJ8NDkBlQIQeFfeaBCqbwIvHK5XXXyZagUx5aTBQU
