### Register user
POST http://localhost:3900/auth/register
Content-Type: application/json

{
    "fullName": "Kenny Maina",
    "email": "dkings@yopmail.com",
    "password": "12345678"
}

### login a user
POST http://localhost:3900/auth/login
Content-Type: application/json

{
    "email": "dkings@yopmail.com",
    "password": "12345678"
}

### validate user
PUT http://localhost:3900/auth/validate-user/19e3c4ab-b756-4aaa-86b8-387921dd6a49