### Create a new industry
POST http://localhost:3900/industry/new
Content-Type: application/json

{
    "industryName": "Software development",
    "industryImage": "../../../assets/stats.png"
}

### Get all industries
GET http://localhost:3900/industry/all

### Delete industry
DELETE http://localhost:3900/industry/delete/fdd81c24-91ac-4151-b24f-4a7b095d1316