### set user role
PUT http://localhost:3900/users/set-role/b287f56f-09aa-4f5e-a5e8-d6d8168dd430
Content-Type: application/json

{
    "role": "specialist"
}

### Update user
PUT http://localhost:3900/users/update-details/9f4fdb06-4726-426a-b608-6cbc4f4bd306
Content-Type: application/json

{
    "gender": "female",
    "DOB": "2/12/2024",
    "about": "I am me",
    "country": "Kenya",
    "city": "Nairobi",
    "industry": "0c3a4c91-d3c2-4c58-9018-0919bca5be78",
    "phoneNumber": "0708530896",
    "bankAcNo": 12356789,
    "bankAcName": "Kivu branch"
}

### Get all users
GET http://localhost:3900/users/all-users

### Get one user
GET http://localhost:3900/users/one-user/22c7af21-be93-47f9-b190-6c5514b512dc

### Delete a user and their details
DELETE http://localhost:3900/users/delete-user/376ba56d-0fc3-41f8-8e03-702dfef73b8f

### Get user's details
GET http://localhost:3900/users/details/382606d6-e405-4323-8352-d3dc4d34d574


### Get all specialists
GET http://localhost:3900/users/all-specialists